//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto.subscriber;

import com.actility.thingpark.smp.rest.dto.OccContext;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for AddressDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AddressDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.actility.com/smp/ws/common}AddressType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="occContext" type="{http://www.actility.com/smp/ws/common}OccContext"/&gt;
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressDto", propOrder = {
        "typeIndicator",
        "personalName",
        "name",
        "address1",
        "address2",
        "city",
        "region",
        "zip",
        "country",
        "contactPhone",
        "contactInfo",
        "occContext",
        "id"
})
@XmlRootElement(namespace = "http://www.actility.com/smp/ws/subscriber", name = "address")
public class AddressDto {

  @XmlElement(required = true)
  protected String typeIndicator;
  @XmlElement(required = true)
  protected String personalName;
  @XmlElement(required = true)
  protected String name;
  @XmlElement(required = true)
  protected String address1;
  @XmlElement(required = true)
  protected String address2;
  @XmlElement(required = true)
  protected String city;
  @XmlElement(required = true)
  protected String region;
  @XmlElement(required = true)
  protected String zip;
  @XmlElement(required = true)
  protected String country;
  @XmlElement(required = true)
  protected String contactPhone;
  @XmlElement(required = true)
  protected String contactInfo;
  @XmlElement(required = true)
  protected OccContext occContext;
  @XmlElement(name = "ID", required = true)
  protected String id;

  /**
   * Default no-arg constructor
   */
  public AddressDto() {
  }

  /**
   * Fully-initialising value constructor
   */
  public AddressDto(final String typeIndicator, final String personalName, final String name, final String address1, final String address2, final String city, final String region, final String zip, final String country, final String contactPhone, final String contactInfo, final OccContext occContext, final String id) {
    this.typeIndicator = typeIndicator;
    this.personalName = personalName;
    this.name = name;
    this.address1 = address1;
    this.address2 = address2;
    this.city = city;
    this.region = region;
    this.zip = zip;
    this.country = country;
    this.contactPhone = contactPhone;
    this.contactInfo = contactInfo;
    this.occContext = occContext;
    this.id = id;
  }

  /**
   * Gets the value of the typeIndicator property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getTypeIndicator() {
    return typeIndicator;
  }

  /**
   * Sets the value of the typeIndicator property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setTypeIndicator(String value) {
    this.typeIndicator = value;
  }

  /**
   * Gets the value of the personalName property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getPersonalName() {
    return personalName;
  }

  /**
   * Sets the value of the personalName property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setPersonalName(String value) {
    this.personalName = value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the address1 property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getAddress1() {
    return address1;
  }

  /**
   * Sets the value of the address1 property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAddress1(String value) {
    this.address1 = value;
  }

  /**
   * Gets the value of the address2 property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getAddress2() {
    return address2;
  }

  /**
   * Sets the value of the address2 property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAddress2(String value) {
    this.address2 = value;
  }

  /**
   * Gets the value of the city property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getCity() {
    return city;
  }

  /**
   * Sets the value of the city property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setCity(String value) {
    this.city = value;
  }

  /**
   * Gets the value of the region property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getRegion() {
    return region;
  }

  /**
   * Sets the value of the region property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setRegion(String value) {
    this.region = value;
  }

  /**
   * Gets the value of the zip property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getZip() {
    return zip;
  }

  /**
   * Sets the value of the zip property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setZip(String value) {
    this.zip = value;
  }

  /**
   * Gets the value of the country property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getCountry() {
    return country;
  }

  /**
   * Sets the value of the country property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setCountry(String value) {
    this.country = value;
  }

  /**
   * Gets the value of the contactPhone property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getContactPhone() {
    return contactPhone;
  }

  /**
   * Sets the value of the contactPhone property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setContactPhone(String value) {
    this.contactPhone = value;
  }

  /**
   * Gets the value of the contactInfo property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getContactInfo() {
    return contactInfo;
  }

  /**
   * Sets the value of the contactInfo property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setContactInfo(String value) {
    this.contactInfo = value;
  }

  /**
   * Gets the value of the occContext property.
   *
   * @return possible object is
   * {@link OccContext }
   */
  public OccContext getOccContext() {
    return occContext;
  }

  /**
   * Sets the value of the occContext property.
   *
   * @param value allowed object is
   *              {@link OccContext }
   */
  public void setOccContext(OccContext value) {
    this.occContext = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getID() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setID(String value) {
    this.id = value;
  }

  public AddressDto withOccContext(OccContext value) {
    setOccContext(value);
    return this;
  }

  public AddressDto withID(String value) {
    setID(value);
    return this;
  }

  public AddressDto withTypeIndicator(String value) {
    setTypeIndicator(value);
    return this;
  }

  public AddressDto withPersonalName(String value) {
    setPersonalName(value);
    return this;
  }

  public AddressDto withName(String value) {
    setName(value);
    return this;
  }

  public AddressDto withAddress1(String value) {
    setAddress1(value);
    return this;
  }

  public AddressDto withAddress2(String value) {
    setAddress2(value);
    return this;
  }

  public AddressDto withCity(String value) {
    setCity(value);
    return this;
  }

  public AddressDto withRegion(String value) {
    setRegion(value);
    return this;
  }

  public AddressDto withZip(String value) {
    setZip(value);
    return this;
  }

  public AddressDto withCountry(String value) {
    setCountry(value);
    return this;
  }

  public AddressDto withContactPhone(String value) {
    setContactPhone(value);
    return this;
  }

  public AddressDto withContactInfo(String value) {
    setContactInfo(value);
    return this;
  }

}
