//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto.user;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for AccessCodeDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AccessCodeDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="applicationID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="accessCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessCodeDto", propOrder = {
        "applicationID",
        "accessCode"
})
@XmlRootElement(namespace = "http://www.actility.com/smp/ws/user", name = "accessCode")
public class AccessCodeDto {

  @XmlElement(required = true)
  protected String applicationID;
  @XmlElement(required = true)
  protected String accessCode;

  /**
   * Default no-arg constructor
   */
  public AccessCodeDto() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public AccessCodeDto(final String applicationID, final String accessCode) {
    this.applicationID = applicationID;
    this.accessCode = accessCode;
  }

  /**
   * Gets the value of the applicationID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getApplicationID() {
    return applicationID;
  }

  /**
   * Sets the value of the applicationID property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setApplicationID(String value) {
    this.applicationID = value;
  }

  /**
   * Gets the value of the accessCode property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getAccessCode() {
    return accessCode;
  }

  /**
   * Sets the value of the accessCode property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAccessCode(String value) {
    this.accessCode = value;
  }

  public AccessCodeDto withApplicationID(String value) {
    setApplicationID(value);
    return this;
  }

  public AccessCodeDto withAccessCode(String value) {
    setAccessCode(value);
    return this;
  }

}
