//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto.system;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for OperatorsDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OperatorsDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="briefs"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="brief" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="href" type="{http://www.actility.com/smp/ws/common}Ref"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="more" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperatorsDto", propOrder = {
        "briefs",
        "more"
})
@XmlRootElement(namespace = "http://www.actility.com/smp/ws/system", name = "operators")
public class OperatorsDto {

  @XmlElement(required = true)
  protected Briefs briefs;
  protected boolean more;

  /**
   * Default no-arg constructor
   */
  public OperatorsDto() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public OperatorsDto(final Briefs briefs, final boolean more) {
    this.briefs = briefs;
    this.more = more;
  }

  /**
   * Gets the value of the briefs property.
   *
   * @return possible object is
   * {@link Briefs }
   */
  public Briefs getBriefs() {
    return briefs;
  }

  /**
   * Sets the value of the briefs property.
   *
   * @param value allowed object is
   *              {@link Briefs }
   */
  public void setBriefs(Briefs value) {
    this.briefs = value;
  }

  /**
   * Gets the value of the more property.
   */
  public boolean isMore() {
    return more;
  }

  /**
   * Sets the value of the more property.
   */
  public void setMore(boolean value) {
    this.more = value;
  }

  public OperatorsDto withBriefs(Briefs value) {
    setBriefs(value);
    return this;
  }

  public OperatorsDto withMore(boolean value) {
    setMore(value);
    return this;
  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="brief" maxOccurs="unbounded" minOccurs="0"&gt;
   *           &lt;complexType&gt;
   *             &lt;complexContent&gt;
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                 &lt;sequence&gt;
   *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                   &lt;element name="href" type="{http://www.actility.com/smp/ws/common}Ref"/&gt;
   *                 &lt;/sequence&gt;
   *               &lt;/restriction&gt;
   *             &lt;/complexContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "brief"
  })
  public static class Briefs {

    protected List<Brief> brief;

    /**
     * Default no-arg constructor
     */
    public Briefs() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Briefs(final List<Brief> brief) {
      this.brief = brief;
    }

    /**
     * Gets the value of the brief property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the brief property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBrief().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Brief }
     */
    public List<Brief> getBrief() {
      if (brief == null) {
        brief = new ArrayList<>();
      }
      return this.brief;
    }

    public Briefs withBrief(Brief... values) {
      if (values != null) {
        for (Brief value : values) {
          getBrief().add(value);
        }
      }
      return this;
    }

    public Briefs withBrief(Collection<Brief> values) {
      if (values != null) {
        getBrief().addAll(values);
      }
      return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="href" type="{http://www.actility.com/smp/ws/common}Ref"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "name",
            "description",
            "id",
            "href"
    })
    public static class Brief {

      @XmlElement(required = true)
      protected String name;
      @XmlElement(required = true)
      protected String description;
      @XmlElement(name = "ID", required = true)
      protected String id;
      @XmlElement(required = true)
      @XmlSchemaType(name = "anyURI")
      protected String href;

      /**
       * Default no-arg constructor
       */
      public Brief() {
        super();
      }

      /**
       * Fully-initialising value constructor
       */
      public Brief(final String name, final String description, final String id, final String href) {
        this.name = name;
        this.description = description;
        this.id = id;
        this.href = href;
      }

      /**
       * Gets the value of the name property.
       *
       * @return possible object is
       * {@link String }
       */
      public String getName() {
        return name;
      }

      /**
       * Sets the value of the name property.
       *
       * @param value allowed object is
       *              {@link String }
       */
      public void setName(String value) {
        this.name = value;
      }

      /**
       * Gets the value of the description property.
       *
       * @return possible object is
       * {@link String }
       */
      public String getDescription() {
        return description;
      }

      /**
       * Sets the value of the description property.
       *
       * @param value allowed object is
       *              {@link String }
       */
      public void setDescription(String value) {
        this.description = value;
      }

      /**
       * Gets the value of the id property.
       *
       * @return possible object is
       * {@link String }
       */
      public String getID() {
        return id;
      }

      /**
       * Sets the value of the id property.
       *
       * @param value allowed object is
       *              {@link String }
       */
      public void setID(String value) {
        this.id = value;
      }

      /**
       * Gets the value of the href property.
       *
       * @return possible object is
       * {@link String }
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       *
       * @param value allowed object is
       *              {@link String }
       */
      public void setHref(String value) {
        this.href = value;
      }

      public Brief withName(String value) {
        setName(value);
        return this;
      }

      public Brief withDescription(String value) {
        setDescription(value);
        return this;
      }

      public Brief withID(String value) {
        setID(value);
        return this;
      }

      public Brief withHref(String value) {
        setHref(value);
        return this;
      }

    }

  }

}
