//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeatureDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FeatureDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="val" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureDto")
public class FeatureDto {

  @XmlAttribute(name = "name")
  protected String name;
  @XmlAttribute(name = "val")
  protected String val;

  /**
   * Default no-arg constructor
   */
  public FeatureDto() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public FeatureDto(final String name, final String val) {
    this.name = name;
    this.val = val;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the val property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getVal() {
    return val;
  }

  /**
   * Sets the value of the val property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setVal(String value) {
    this.val = value;
  }

  public FeatureDto withName(String value) {
    setName(value);
    return this;
  }

  public FeatureDto withVal(String value) {
    setVal(value);
    return this;
  }

}
