//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OccContext complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OccContext"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="version" type="{http://www.actility.com/smp/ws/common}OccVersion"/&gt;
 *         &lt;element name="lastUpdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="who" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OccContext", propOrder = {
        "version",
        "lastUpdate",
        "who"
})
public class OccContext {

  protected long version;
  @XmlElement(required = true, nillable = true)
  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar lastUpdate;
  @XmlElement(required = true)
  protected String who;

  /**
   * Default no-arg constructor
   */
  public OccContext() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public OccContext(final long version, final XMLGregorianCalendar lastUpdate, final String who) {
    this.version = version;
    this.lastUpdate = lastUpdate;
    this.who = who;
  }

  /**
   * Gets the value of the version property.
   */
  public long getVersion() {
    return version;
  }

  /**
   * Sets the value of the version property.
   */
  public void setVersion(long value) {
    this.version = value;
  }

  /**
   * Gets the value of the lastUpdate property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getLastUpdate() {
    return lastUpdate;
  }

  /**
   * Sets the value of the lastUpdate property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setLastUpdate(XMLGregorianCalendar value) {
    this.lastUpdate = value;
  }

  /**
   * Gets the value of the who property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getWho() {
    return who;
  }

  /**
   * Sets the value of the who property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setWho(String value) {
    this.who = value;
  }

  public OccContext withVersion(long value) {
    setVersion(value);
    return this;
  }

  public OccContext withLastUpdate(XMLGregorianCalendar value) {
    setLastUpdate(value);
    return this;
  }

  public OccContext withWho(String value) {
    setWho(value);
    return this;
  }

}
