//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.11.28 at 03:08:24 PM CET
//


package com.actility.thingpark.smp.rest.dto.admin;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for LoginDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LoginDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.actility.com/smp/ws/common}LoginType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="thingparkID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="domain" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoginDto", propOrder = {
        "login",
        "password",
        "sessionToken",
        "thingparkID",
        "domain"
})
@XmlRootElement(namespace = "http://www.actility.com/smp/ws/admin", name = "login")
public class LoginDto {

  @XmlElement(required = true)
  protected String login;
  @XmlElement(required = true)
  protected String password;
  @XmlElement(required = true)
  protected String sessionToken;
  @XmlElement(required = true)
  protected String thingparkID;
  @XmlElement(required = true)
  protected String domain;

  /**
   * Default no-arg constructor
   */
  public LoginDto() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public LoginDto(final String login, final String password, final String sessionToken, final String thingparkID, final String domain) {
    this.login = login;
    this.password = password;
    this.sessionToken = sessionToken;
    this.thingparkID = thingparkID;
    this.domain = domain;
  }

  /**
   * Gets the value of the login property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getLogin() {
    return login;
  }

  /**
   * Sets the value of the login property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setLogin(String value) {
    this.login = value;
  }

  /**
   * Gets the value of the password property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getPassword() {
    return password;
  }

  /**
   * Sets the value of the password property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setPassword(String value) {
    this.password = value;
  }

  /**
   * Gets the value of the sessionToken property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getSessionToken() {
    return sessionToken;
  }

  /**
   * Sets the value of the sessionToken property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setSessionToken(String value) {
    this.sessionToken = value;
  }

  /**
   * Gets the value of the thingparkID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getThingparkID() {
    return thingparkID;
  }

  /**
   * Sets the value of the thingparkID property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setThingparkID(String value) {
    this.thingparkID = value;
  }

  /**
   * Gets the value of the domain property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getDomain() {
    return domain;
  }

  /**
   * Sets the value of the domain property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setDomain(String value) {
    this.domain = value;
  }

  public LoginDto withThingparkID(String value) {
    setThingparkID(value);
    return this;
  }

  public LoginDto withDomain(String value) {
    setDomain(value);
    return this;
  }

  public LoginDto withLogin(String value) {
    setLogin(value);
    return this;
  }

  public LoginDto withPassword(String value) {
    setPassword(value);
    return this;
  }

  public LoginDto withSessionToken(String value) {
    setSessionToken(value);
    return this;
  }

}
