//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto.admin;

import com.actility.thingpark.smp.rest.dto.OccContext;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for UserAccountDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UserAccountDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.actility.com/smp/ws/common}UserType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="occContext" type="{http://www.actility.com/smp/ws/common}OccContext"/&gt;
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="lastConnection" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="thingparkLogin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="thingparkBadConsecutivePwd" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="previousConnection" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="thingparkLastUnsuccessfulLogin" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="thingparkPreviousBadConsecutivePwd" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="disclaimerMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="disclaimerRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserAccountDto", propOrder = {
        "gender",
        "firstName",
        "lastName",
        "language",
        "email",
        "mobilePhone",
        "officePhone",
        "homePhone",
        "organization",
        "address",
        "city",
        "region",
        "zip",
        "country",
        "thingparkID",
        "facebookID",
        "googleID",
        "occContext",
        "state",
        "lastConnection",
        "thingparkLogin",
        "thingparkBadConsecutivePwd",
        "previousConnection",
        "thingparkLastUnsuccessfulLogin",
        "thingparkPreviousBadConsecutivePwd",
        "disclaimerMessage",
        "disclaimerRequired"
})
public class UserAccountDto {

  @XmlElement(required = true)
  protected String gender;
  @XmlElement(required = true)
  protected String firstName;
  @XmlElement(required = true)
  protected String lastName;
  @XmlElement(required = true)
  protected String language;
  @XmlElement(required = true)
  protected String email;
  @XmlElement(required = true)
  protected String mobilePhone;
  @XmlElement(required = true)
  protected String officePhone;
  @XmlElement(required = true)
  protected String homePhone;
  @XmlElement(required = true)
  protected String organization;
  @XmlElement(required = true)
  protected String address;
  @XmlElement(required = true)
  protected String city;
  @XmlElement(required = true)
  protected String region;
  @XmlElement(required = true)
  protected String zip;
  @XmlElement(required = true)
  protected String country;
  @XmlElement(required = true)
  protected String thingparkID;
  @XmlElement(required = true)
  protected String facebookID;
  @XmlElement(required = true)
  protected String googleID;
  @XmlElement(required = true)
  protected OccContext occContext;
  @XmlElement(required = true)
  protected String state;
  @XmlElement(required = true)
  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar lastConnection;
  @XmlElement(required = true)
  protected String thingparkLogin;
  protected int thingparkBadConsecutivePwd;
  @XmlElement(required = true)
  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar previousConnection;
  @XmlElement(required = true)
  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar thingparkLastUnsuccessfulLogin;
  protected int thingparkPreviousBadConsecutivePwd;
  @XmlElement(required = true)
  protected String disclaimerMessage;
  protected boolean disclaimerRequired;
  protected boolean apiOnly;

  /**
   * Default no-arg constructor
   */
  public UserAccountDto() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public UserAccountDto(final String gender, final String firstName, final String lastName, final String language,
                        final String email, final String mobilePhone, final String officePhone, final String homePhone,
                        final String organization, final String address, final String city, final String region, final String zip,
                        final String country, final String thingparkID, final String facebookID, final String googleID,
                        final OccContext occContext, final String state, final XMLGregorianCalendar lastConnection,
                        final String thingparkLogin, final int thingparkBadConsecutivePwd, final XMLGregorianCalendar previousConnection,
                        final XMLGregorianCalendar thingparkLastUnsuccessfulLogin, final int thingparkPreviousBadConsecutivePwd,
                        final String disclaimerMessage, final boolean disclaimerRequired, final boolean apiOnly) {
    this.gender = gender;
    this.firstName = firstName;
    this.lastName = lastName;
    this.language = language;
    this.email = email;
    this.mobilePhone = mobilePhone;
    this.officePhone = officePhone;
    this.homePhone = homePhone;
    this.organization = organization;
    this.address = address;
    this.city = city;
    this.region = region;
    this.zip = zip;
    this.country = country;
    this.thingparkID = thingparkID;
    this.facebookID = facebookID;
    this.googleID = googleID;
    this.occContext = occContext;
    this.state = state;
    this.lastConnection = lastConnection;
    this.thingparkLogin = thingparkLogin;
    this.thingparkBadConsecutivePwd = thingparkBadConsecutivePwd;
    this.previousConnection = previousConnection;
    this.thingparkLastUnsuccessfulLogin = thingparkLastUnsuccessfulLogin;
    this.thingparkPreviousBadConsecutivePwd = thingparkPreviousBadConsecutivePwd;
    this.disclaimerMessage = disclaimerMessage;
    this.disclaimerRequired = disclaimerRequired;
    this.apiOnly = apiOnly;
  }

  /**
   * Gets the value of the gender property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getGender() {
    return gender;
  }

  /**
   * Sets the value of the gender property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setGender(String value) {
    this.gender = value;
  }

  /**
   * Gets the value of the firstName property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the firstName property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setFirstName(String value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the lastName property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the lastName property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setLastName(String value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the language property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getLanguage() {
    return language;
  }

  /**
   * Sets the value of the language property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setLanguage(String value) {
    this.language = value;
  }

  /**
   * Gets the value of the email property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getEmail() {
    return email;
  }

  /**
   * Sets the value of the email property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setEmail(String value) {
    this.email = value;
  }

  /**
   * Gets the value of the mobilePhone property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getMobilePhone() {
    return mobilePhone;
  }

  /**
   * Sets the value of the mobilePhone property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setMobilePhone(String value) {
    this.mobilePhone = value;
  }

  /**
   * Gets the value of the officePhone property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getOfficePhone() {
    return officePhone;
  }

  /**
   * Sets the value of the officePhone property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setOfficePhone(String value) {
    this.officePhone = value;
  }

  /**
   * Gets the value of the homePhone property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getHomePhone() {
    return homePhone;
  }

  /**
   * Sets the value of the homePhone property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setHomePhone(String value) {
    this.homePhone = value;
  }

  /**
   * Gets the value of the organization property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getOrganization() {
    return organization;
  }

  /**
   * Sets the value of the organization property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setOrganization(String value) {
    this.organization = value;
  }

  /**
   * Gets the value of the address property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getAddress() {
    return address;
  }

  /**
   * Sets the value of the address property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAddress(String value) {
    this.address = value;
  }

  /**
   * Gets the value of the city property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getCity() {
    return city;
  }

  /**
   * Sets the value of the city property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setCity(String value) {
    this.city = value;
  }

  /**
   * Gets the value of the region property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getRegion() {
    return region;
  }

  /**
   * Sets the value of the region property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setRegion(String value) {
    this.region = value;
  }

  /**
   * Gets the value of the zip property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getZip() {
    return zip;
  }

  /**
   * Sets the value of the zip property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setZip(String value) {
    this.zip = value;
  }

  /**
   * Gets the value of the country property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getCountry() {
    return country;
  }

  /**
   * Sets the value of the country property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setCountry(String value) {
    this.country = value;
  }

  /**
   * Gets the value of the thingparkID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getThingparkID() {
    return thingparkID;
  }

  /**
   * Sets the value of the thingparkID property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setThingparkID(String value) {
    this.thingparkID = value;
  }

  /**
   * Gets the value of the facebookID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getFacebookID() {
    return facebookID;
  }

  /**
   * Sets the value of the facebookID property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setFacebookID(String value) {
    this.facebookID = value;
  }

  /**
   * Gets the value of the googleID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getGoogleID() {
    return googleID;
  }

  /**
   * Sets the value of the googleID property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setGoogleID(String value) {
    this.googleID = value;
  }

  /**
   * Gets the value of the occContext property.
   *
   * @return possible object is
   * {@link OccContext }
   */
  public OccContext getOccContext() {
    return occContext;
  }

  /**
   * Sets the value of the occContext property.
   *
   * @param value allowed object is
   *              {@link OccContext }
   */
  public void setOccContext(OccContext value) {
    this.occContext = value;
  }

  /**
   * Gets the value of the state property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getState() {
    return state;
  }

  /**
   * Sets the value of the state property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setState(String value) {
    this.state = value;
  }

  /**
   * Gets the value of the lastConnection property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getLastConnection() {
    return lastConnection;
  }

  /**
   * Sets the value of the lastConnection property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setLastConnection(XMLGregorianCalendar value) {
    this.lastConnection = value;
  }

  /**
   * Gets the value of the thingparkLogin property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getThingparkLogin() {
    return thingparkLogin;
  }

  /**
   * Sets the value of the thingparkLogin property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setThingparkLogin(String value) {
    this.thingparkLogin = value;
  }

  /**
   * Gets the value of the thingparkBadConsecutivePwd property.
   */
  public int getThingparkBadConsecutivePwd() {
    return thingparkBadConsecutivePwd;
  }

  /**
   * Sets the value of the thingparkBadConsecutivePwd property.
   */
  public void setThingparkBadConsecutivePwd(int value) {
    this.thingparkBadConsecutivePwd = value;
  }

  /**
   * Gets the value of the previousConnection property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getPreviousConnection() {
    return previousConnection;
  }

  /**
   * Sets the value of the previousConnection property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setPreviousConnection(XMLGregorianCalendar value) {
    this.previousConnection = value;
  }

  /**
   * Gets the value of the thingparkLastUnsuccessfulLogin property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getThingparkLastUnsuccessfulLogin() {
    return thingparkLastUnsuccessfulLogin;
  }

  /**
   * Sets the value of the thingparkLastUnsuccessfulLogin property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setThingparkLastUnsuccessfulLogin(XMLGregorianCalendar value) {
    this.thingparkLastUnsuccessfulLogin = value;
  }

  /**
   * Gets the value of the thingparkPreviousBadConsecutivePwd property.
   */
  public int getThingparkPreviousBadConsecutivePwd() {
    return thingparkPreviousBadConsecutivePwd;
  }

  /**
   * Sets the value of the thingparkPreviousBadConsecutivePwd property.
   */
  public void setThingparkPreviousBadConsecutivePwd(int value) {
    this.thingparkPreviousBadConsecutivePwd = value;
  }

  /**
   * Gets the value of the disclaimerMessage property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getDisclaimerMessage() {
    return disclaimerMessage;
  }

  /**
   * Sets the value of the disclaimerMessage property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setDisclaimerMessage(String value) {
    this.disclaimerMessage = value;
  }

  /**
   * Gets the value of the disclaimerRequired property.
   */
  public boolean isDisclaimerRequired() {
    return disclaimerRequired;
  }

  /**
   * Sets the value of the disclaimerRequired property.
   */
  public void setDisclaimerRequired(boolean value) {
    this.disclaimerRequired = value;
  }

  /**
   * Obtient la valeur de la propriété apiOnly.
   *
   */
  public boolean isApiOnly() {
    return apiOnly;
  }

  /**
   * Définit la valeur de la propriété apiOnly.
   *
   */
  public void setApiOnly(boolean value) {
    this.apiOnly = value;
  }

  public UserAccountDto withGender(String value) {
    setGender(value);
    return this;
  }

  public UserAccountDto withFirstName(String value) {
    setFirstName(value);
    return this;
  }

  public UserAccountDto withLastName(String value) {
    setLastName(value);
    return this;
  }

  public UserAccountDto withLanguage(String value) {
    setLanguage(value);
    return this;
  }

  public UserAccountDto withEmail(String value) {
    setEmail(value);
    return this;
  }

  public UserAccountDto withMobilePhone(String value) {
    setMobilePhone(value);
    return this;
  }

  public UserAccountDto withOfficePhone(String value) {
    setOfficePhone(value);
    return this;
  }

  public UserAccountDto withHomePhone(String value) {
    setHomePhone(value);
    return this;
  }

  public UserAccountDto withOrganization(String value) {
    setOrganization(value);
    return this;
  }

  public UserAccountDto withAddress(String value) {
    setAddress(value);
    return this;
  }

  public UserAccountDto withCity(String value) {
    setCity(value);
    return this;
  }

  public UserAccountDto withRegion(String value) {
    setRegion(value);
    return this;
  }

  public UserAccountDto withZip(String value) {
    setZip(value);
    return this;
  }

  public UserAccountDto withCountry(String value) {
    setCountry(value);
    return this;
  }

  public UserAccountDto withThingparkID(String value) {
    setThingparkID(value);
    return this;
  }

  public UserAccountDto withFacebookID(String value) {
    setFacebookID(value);
    return this;
  }

  public UserAccountDto withGoogleID(String value) {
    setGoogleID(value);
    return this;
  }

  public UserAccountDto withOccContext(OccContext value) {
    setOccContext(value);
    return this;
  }

  public UserAccountDto withState(String value) {
    setState(value);
    return this;
  }

  public UserAccountDto withLastConnection(XMLGregorianCalendar value) {
    setLastConnection(value);
    return this;
  }

  public UserAccountDto withThingparkLogin(String value) {
    setThingparkLogin(value);
    return this;
  }

  public UserAccountDto withThingparkBadConsecutivePwd(int value) {
    setThingparkBadConsecutivePwd(value);
    return this;
  }

  public UserAccountDto withPreviousConnection(XMLGregorianCalendar value) {
    setPreviousConnection(value);
    return this;
  }

  public UserAccountDto withThingparkLastUnsuccessfulLogin(XMLGregorianCalendar value) {
    setThingparkLastUnsuccessfulLogin(value);
    return this;
  }

  public UserAccountDto withThingparkPreviousBadConsecutivePwd(int value) {
    setThingparkPreviousBadConsecutivePwd(value);
    return this;
  }

  public UserAccountDto withDisclaimerMessage(String value) {
    setDisclaimerMessage(value);
    return this;
  }

  public UserAccountDto withDisclaimerRequired(boolean value) {
    setDisclaimerRequired(value);
    return this;
  }

}
