//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto.application;

import com.actility.thingpark.smp.rest.dto.FeatureDto;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for SubscribedDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SubscribedDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transactionID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="subscriber"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="extID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="operator"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="supplier"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="vendor"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="features"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="feature" type="{http://www.actility.com/smp/ws/common}FeatureDto" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscribedDto", propOrder = {
        "transactionID",
        "operation",
        "subscriber",
        "operator",
        "supplier",
        "vendor",
        "features",
        "href"
})
@XmlRootElement(namespace = "http://www.actility.com/smp/ws/application", name = "subscribed")
public class SubscribedDto {

  @XmlElement(required = true)
  protected String transactionID;
  @XmlElement(required = true)
  protected String operation;
  @XmlElement(required = true)
  protected Subscriber subscriber;
  @XmlElement(required = true)
  protected Operator operator;
  @XmlElement(required = true)
  protected Supplier supplier;
  @XmlElement(required = true)
  protected Vendor vendor;
  @XmlElement(required = true)
  protected Features features;
  @XmlElement(required = true)
  protected String href;

  /**
   * Default no-arg constructor
   */
  public SubscribedDto() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public SubscribedDto(final String transactionID, final String operation, final Subscriber subscriber, final Operator operator, final Supplier supplier, final Vendor vendor, final Features features, final String href) {
    this.transactionID = transactionID;
    this.operation = operation;
    this.subscriber = subscriber;
    this.operator = operator;
    this.supplier = supplier;
    this.vendor = vendor;
    this.features = features;
    this.href = href;
  }

  /**
   * Gets the value of the transactionID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getTransactionID() {
    return transactionID;
  }

  /**
   * Sets the value of the transactionID property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setTransactionID(String value) {
    this.transactionID = value;
  }

  /**
   * Gets the value of the operation property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getOperation() {
    return operation;
  }

  /**
   * Sets the value of the operation property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setOperation(String value) {
    this.operation = value;
  }

  /**
   * Gets the value of the subscriber property.
   *
   * @return possible object is
   * {@link Subscriber }
   */
  public Subscriber getSubscriber() {
    return subscriber;
  }

  /**
   * Sets the value of the subscriber property.
   *
   * @param value allowed object is
   *              {@link Subscriber }
   */
  public void setSubscriber(Subscriber value) {
    this.subscriber = value;
  }

  /**
   * Gets the value of the operator property.
   *
   * @return possible object is
   * {@link Operator }
   */
  public Operator getOperator() {
    return operator;
  }

  /**
   * Sets the value of the operator property.
   *
   * @param value allowed object is
   *              {@link Operator }
   */
  public void setOperator(Operator value) {
    this.operator = value;
  }

  /**
   * Gets the value of the supplier property.
   *
   * @return possible object is
   * {@link Supplier }
   */
  public Supplier getSupplier() {
    return supplier;
  }

  /**
   * Sets the value of the supplier property.
   *
   * @param value allowed object is
   *              {@link Supplier }
   */
  public void setSupplier(Supplier value) {
    this.supplier = value;
  }

  /**
   * Gets the value of the vendor property.
   *
   * @return possible object is
   * {@link Vendor }
   */
  public Vendor getVendor() {
    return vendor;
  }

  /**
   * Sets the value of the vendor property.
   *
   * @param value allowed object is
   *              {@link Vendor }
   */
  public void setVendor(Vendor value) {
    this.vendor = value;
  }

  /**
   * Gets the value of the features property.
   *
   * @return possible object is
   * {@link Features }
   */
  public Features getFeatures() {
    return features;
  }

  /**
   * Sets the value of the features property.
   *
   * @param value allowed object is
   *              {@link Features }
   */
  public void setFeatures(Features value) {
    this.features = value;
  }

  /**
   * Gets the value of the href property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getHref() {
    return href;
  }

  /**
   * Sets the value of the href property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setHref(String value) {
    this.href = value;
  }

  public SubscribedDto withTransactionID(String value) {
    setTransactionID(value);
    return this;
  }

  public SubscribedDto withOperation(String value) {
    setOperation(value);
    return this;
  }

  public SubscribedDto withSubscriber(Subscriber value) {
    setSubscriber(value);
    return this;
  }

  public SubscribedDto withOperator(Operator value) {
    setOperator(value);
    return this;
  }

  public SubscribedDto withSupplier(Supplier value) {
    setSupplier(value);
    return this;
  }

  public SubscribedDto withVendor(Vendor value) {
    setVendor(value);
    return this;
  }

  public SubscribedDto withFeatures(Features value) {
    setFeatures(value);
    return this;
  }

  public SubscribedDto withHref(String value) {
    setHref(value);
    return this;
  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="feature" type="{http://www.actility.com/smp/ws/common}FeatureDto" maxOccurs="unbounded"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "feature"
  })
  public static class Features {

    @XmlElement(required = true)
    protected List<FeatureDto> feature;

    /**
     * Default no-arg constructor
     */
    public Features() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Features(final List<FeatureDto> feature) {
      this.feature = feature;
    }

    /**
     * Gets the value of the feature property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feature property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeature().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureDto }
     */
    public List<FeatureDto> getFeature() {
      if (feature == null) {
        feature = new ArrayList<>();
      }
      return this.feature;
    }

    public Features withFeature(FeatureDto... values) {
      if (values != null) {
        for (FeatureDto value : values) {
          getFeature().add(value);
        }
      }
      return this;
    }

    public Features withFeature(Collection<FeatureDto> values) {
      if (values != null) {
        getFeature().addAll(values);
      }
      return this;
    }

  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "id"
  })
  public static class Operator {

    @XmlElement(name = "ID", required = true)
    protected String id;

    /**
     * Default no-arg constructor
     */
    public Operator() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Operator(final String id) {
      this.id = id;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
      return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(String value) {
      this.id = value;
    }

    public Operator withID(String value) {
      setID(value);
      return this;
    }

  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="extID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "name",
          "id",
          "extID",
          "type"
  })
  public static class Subscriber {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(required = true)
    protected String extID;
    @XmlElement(required = true)
    protected String type;

    /**
     * Default no-arg constructor
     */
    public Subscriber() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Subscriber(final String name, final String id, final String extID, final String type) {
      this.name = name;
      this.id = id;
      this.extID = extID;
      this.type = type;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
      return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
      this.name = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
      return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(String value) {
      this.id = value;
    }

    /**
     * Gets the value of the extID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExtID() {
      return extID;
    }

    /**
     * Sets the value of the extID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExtID(String value) {
      this.extID = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
      return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
      this.type = value;
    }

    public Subscriber withName(String value) {
      setName(value);
      return this;
    }

    public Subscriber withID(String value) {
      setID(value);
      return this;
    }

    public Subscriber withExtID(String value) {
      setExtID(value);
      return this;
    }

    public Subscriber withType(String value) {
      setType(value);
      return this;
    }

  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "id"
  })
  public static class Supplier {

    @XmlElement(name = "ID", required = true)
    protected String id;

    /**
     * Default no-arg constructor
     */
    public Supplier() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Supplier(final String id) {
      this.id = id;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
      return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(String value) {
      this.id = value;
    }

    public Supplier withID(String value) {
      setID(value);
      return this;
    }

  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "id"
  })
  public static class Vendor {

    @XmlElement(name = "ID", required = true)
    protected String id;

    /**
     * Default no-arg constructor
     */
    public Vendor() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Vendor(final String id) {
      this.id = id;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
      return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(String value) {
      this.id = value;
    }

    public Vendor withID(String value) {
      setID(value);
      return this;
    }

  }

}
