//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto.application;

import com.actility.thingpark.smp.rest.dto.StateType;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for SubscriptionDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SubscriptionDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subscriber"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="extID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="contactHomePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="contactMobilePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="contactOfficePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="application"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="grantedPermissions"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="permission" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="state" type="{http://www.actility.com/smp/ws/common}StateType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionDto", propOrder = {
        "subscriber",
        "application"
})
@XmlRootElement(namespace = "http://www.actility.com/smp/ws/application", name = "subscription")
public class SubscriptionDto {

  @XmlElement(required = true)
  protected Subscriber subscriber;
  @XmlElement(required = true)
  protected Application application;

  /**
   * Default no-arg constructor
   */
  public SubscriptionDto() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public SubscriptionDto(final Subscriber subscriber, final Application application) {
    this.subscriber = subscriber;
    this.application = application;
  }

  /**
   * Gets the value of the subscriber property.
   *
   * @return possible object is
   * {@link Subscriber }
   */
  public Subscriber getSubscriber() {
    return subscriber;
  }

  /**
   * Sets the value of the subscriber property.
   *
   * @param value allowed object is
   *              {@link Subscriber }
   */
  public void setSubscriber(Subscriber value) {
    this.subscriber = value;
  }

  /**
   * Gets the value of the application property.
   *
   * @return possible object is
   * {@link Application }
   */
  public Application getApplication() {
    return application;
  }

  /**
   * Sets the value of the application property.
   *
   * @param value allowed object is
   *              {@link Application }
   */
  public void setApplication(Application value) {
    this.application = value;
  }

  public SubscriptionDto withSubscriber(Subscriber value) {
    setSubscriber(value);
    return this;
  }

  public SubscriptionDto withApplication(Application value) {
    setApplication(value);
    return this;
  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="grantedPermissions"&gt;
   *           &lt;complexType&gt;
   *             &lt;complexContent&gt;
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                 &lt;sequence&gt;
   *                   &lt;element name="permission" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
   *                 &lt;/sequence&gt;
   *               &lt;/restriction&gt;
   *             &lt;/complexContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *         &lt;element name="state" type="{http://www.actility.com/smp/ws/common}StateType"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "grantedPermissions",
          "state"
  })
  public static class Application {

    @XmlElement(required = true)
    protected GrantedPermissions grantedPermissions;
    @XmlElement(required = true)
    protected StateType state;

    /**
     * Default no-arg constructor
     */
    public Application() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Application(final GrantedPermissions grantedPermissions, final StateType state) {
      this.grantedPermissions = grantedPermissions;
      this.state = state;
    }

    /**
     * Gets the value of the grantedPermissions property.
     *
     * @return possible object is
     * {@link GrantedPermissions }
     */
    public GrantedPermissions getGrantedPermissions() {
      return grantedPermissions;
    }

    /**
     * Sets the value of the grantedPermissions property.
     *
     * @param value allowed object is
     *              {@link GrantedPermissions }
     */
    public void setGrantedPermissions(GrantedPermissions value) {
      this.grantedPermissions = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     * {@link StateType }
     */
    public StateType getState() {
      return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link StateType }
     */
    public void setState(StateType value) {
      this.state = value;
    }

    public Application withGrantedPermissions(GrantedPermissions value) {
      setGrantedPermissions(value);
      return this;
    }

    public Application withState(StateType value) {
      setState(value);
      return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="permission" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "permission"
    })
    public static class GrantedPermissions {

      protected List<String> permission;

      /**
       * Default no-arg constructor
       */
      public GrantedPermissions() {
        super();
      }

      /**
       * Fully-initialising value constructor
       */
      public GrantedPermissions(final List<String> permission) {
        this.permission = permission;
      }

      /**
       * Gets the value of the permission property.
       *
       * <p>
       * This accessor method returns a reference to the live list,
       * not a snapshot. Therefore any modification you make to the
       * returned list will be present inside the JAXB object.
       * This is why there is not a <CODE>set</CODE> method for the permission property.
       *
       * <p>
       * For example, to add a new item, do as follows:
       * <pre>
       *    getPermission().add(newItem);
       * </pre>
       *
       *
       * <p>
       * Objects of the following type(s) are allowed in the list
       * {@link String }
       */
      public List<String> getPermission() {
        if (permission == null) {
          permission = new ArrayList<>();
        }
        return this.permission;
      }

      public GrantedPermissions withPermission(String... values) {
        if (values != null) {
          for (String value : values) {
            getPermission().add(value);
          }
        }
        return this;
      }

      public GrantedPermissions withPermission(Collection<String> values) {
        if (values != null) {
          getPermission().addAll(values);
        }
        return this;
      }

    }

  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="extID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="contactHomePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="contactMobilePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="contactOfficePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "id",
          "extID",
          "organization",
          "name",
          "contactName",
          "contactEmail",
          "contactHomePhone",
          "contactMobilePhone",
          "contactOfficePhone",
          "language"
  })
  public static class Subscriber {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(required = true)
    protected String extID;
    @XmlElement(required = true)
    protected String organization;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String contactName;
    @XmlElement(required = true)
    protected String contactEmail;
    @XmlElement(required = true)
    protected String contactHomePhone;
    @XmlElement(required = true)
    protected String contactMobilePhone;
    @XmlElement(required = true)
    protected String contactOfficePhone;
    @XmlElement(required = true)
    protected String language;

    /**
     * Default no-arg constructor
     */
    public Subscriber() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Subscriber(final String id, final String extID, final String organization, final String name, final String contactName, final String contactEmail, final String contactHomePhone, final String contactMobilePhone, final String contactOfficePhone, final String language) {
      this.id = id;
      this.extID = extID;
      this.organization = organization;
      this.name = name;
      this.contactName = contactName;
      this.contactEmail = contactEmail;
      this.contactHomePhone = contactHomePhone;
      this.contactMobilePhone = contactMobilePhone;
      this.contactOfficePhone = contactOfficePhone;
      this.language = language;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
      return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(String value) {
      this.id = value;
    }

    /**
     * Gets the value of the extID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExtID() {
      return extID;
    }

    /**
     * Sets the value of the extID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExtID(String value) {
      this.extID = value;
    }

    /**
     * Gets the value of the organization property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrganization() {
      return organization;
    }

    /**
     * Sets the value of the organization property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrganization(String value) {
      this.organization = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
      return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
      this.name = value;
    }

    /**
     * Gets the value of the contactName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContactName() {
      return contactName;
    }

    /**
     * Sets the value of the contactName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContactName(String value) {
      this.contactName = value;
    }

    /**
     * Gets the value of the contactEmail property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContactEmail() {
      return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContactEmail(String value) {
      this.contactEmail = value;
    }

    /**
     * Gets the value of the contactHomePhone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContactHomePhone() {
      return contactHomePhone;
    }

    /**
     * Sets the value of the contactHomePhone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContactHomePhone(String value) {
      this.contactHomePhone = value;
    }

    /**
     * Gets the value of the contactMobilePhone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContactMobilePhone() {
      return contactMobilePhone;
    }

    /**
     * Sets the value of the contactMobilePhone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContactMobilePhone(String value) {
      this.contactMobilePhone = value;
    }

    /**
     * Gets the value of the contactOfficePhone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContactOfficePhone() {
      return contactOfficePhone;
    }

    /**
     * Sets the value of the contactOfficePhone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContactOfficePhone(String value) {
      this.contactOfficePhone = value;
    }

    /**
     * Gets the value of the language property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLanguage() {
      return language;
    }

    /**
     * Sets the value of the language property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLanguage(String value) {
      this.language = value;
    }

    public Subscriber withID(String value) {
      setID(value);
      return this;
    }

    public Subscriber withExtID(String value) {
      setExtID(value);
      return this;
    }

    public Subscriber withOrganization(String value) {
      setOrganization(value);
      return this;
    }

    public Subscriber withName(String value) {
      setName(value);
      return this;
    }

    public Subscriber withContactName(String value) {
      setContactName(value);
      return this;
    }

    public Subscriber withContactEmail(String value) {
      setContactEmail(value);
      return this;
    }

    public Subscriber withContactHomePhone(String value) {
      setContactHomePhone(value);
      return this;
    }

    public Subscriber withContactMobilePhone(String value) {
      setContactMobilePhone(value);
      return this;
    }

    public Subscriber withContactOfficePhone(String value) {
      setContactOfficePhone(value);
      return this;
    }

    public Subscriber withLanguage(String value) {
      setLanguage(value);
      return this;
    }

  }

}
