//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto.application;

import com.actility.thingpark.smp.rest.dto.StateType;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for UpdatedDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UpdatedDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transactionID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="subscriber"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="extID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="application"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="state" type="{http://www.actility.com/smp/ws/common}StateType"/&gt;
 *                   &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdatedDto", propOrder = {
        "transactionID",
        "subscriber",
        "application"
})
@XmlRootElement(namespace = "http://www.actility.com/smp/ws/application", name = "updated")
public class UpdatedDto {

  @XmlElement(required = true)
  protected String transactionID;
  @XmlElement(required = true)
  protected Subscriber subscriber;
  @XmlElement(required = true)
  protected Application application;

  /**
   * Default no-arg constructor
   */
  public UpdatedDto() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public UpdatedDto(final String transactionID, final Subscriber subscriber, final Application application) {
    this.transactionID = transactionID;
    this.subscriber = subscriber;
    this.application = application;
  }

  /**
   * Gets the value of the transactionID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getTransactionID() {
    return transactionID;
  }

  /**
   * Sets the value of the transactionID property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setTransactionID(String value) {
    this.transactionID = value;
  }

  /**
   * Gets the value of the subscriber property.
   *
   * @return possible object is
   * {@link Subscriber }
   */
  public Subscriber getSubscriber() {
    return subscriber;
  }

  /**
   * Sets the value of the subscriber property.
   *
   * @param value allowed object is
   *              {@link Subscriber }
   */
  public void setSubscriber(Subscriber value) {
    this.subscriber = value;
  }

  /**
   * Gets the value of the application property.
   *
   * @return possible object is
   * {@link Application }
   */
  public Application getApplication() {
    return application;
  }

  /**
   * Sets the value of the application property.
   *
   * @param value allowed object is
   *              {@link Application }
   */
  public void setApplication(Application value) {
    this.application = value;
  }

  public UpdatedDto withTransactionID(String value) {
    setTransactionID(value);
    return this;
  }

  public UpdatedDto withSubscriber(Subscriber value) {
    setSubscriber(value);
    return this;
  }

  public UpdatedDto withApplication(Application value) {
    setApplication(value);
    return this;
  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="state" type="{http://www.actility.com/smp/ws/common}StateType"/&gt;
   *         &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "state",
          "href"
  })
  public static class Application {

    @XmlElement(required = true)
    protected StateType state;
    @XmlElement(required = true)
    protected String href;

    /**
     * Default no-arg constructor
     */
    public Application() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Application(final StateType state, final String href) {
      this.state = state;
      this.href = href;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     * {@link StateType }
     */
    public StateType getState() {
      return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link StateType }
     */
    public void setState(StateType value) {
      this.state = value;
    }

    /**
     * Gets the value of the href property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHref() {
      return href;
    }

    /**
     * Sets the value of the href property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHref(String value) {
      this.href = value;
    }

    public Application withState(StateType value) {
      setState(value);
      return this;
    }

    public Application withHref(String value) {
      setHref(value);
      return this;
    }

  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="extID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "id",
          "extID"
  })
  public static class Subscriber {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(required = true)
    protected String extID;

    /**
     * Default no-arg constructor
     */
    public Subscriber() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Subscriber(final String id, final String extID) {
      this.id = id;
      this.extID = extID;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
      return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(String value) {
      this.id = value;
    }

    /**
     * Gets the value of the extID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExtID() {
      return extID;
    }

    /**
     * Sets the value of the extID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExtID(String value) {
      this.extID = value;
    }

    public Subscriber withID(String value) {
      setID(value);
      return this;
    }

    public Subscriber withExtID(String value) {
      setExtID(value);
      return this;
    }

  }

}
