//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto.application;

import com.actility.thingpark.smp.rest.dto.DomainRestrictionsDto;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for UserContextsDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UserContextsDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="briefs"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="brief" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserContextsDto", propOrder = {
        "briefs"
})
@XmlRootElement(namespace = "http://www.actility.com/smp/ws/application", name = "contexts")
public class UserContextsDto {

  @XmlElement(required = true)
  protected Briefs briefs;

  /**
   * Default no-arg constructor
   */
  public UserContextsDto() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public UserContextsDto(final Briefs briefs) {
    this.briefs = briefs;
  }

  /**
   * Gets the value of the briefs property.
   *
   * @return possible object is
   * {@link Briefs }
   */
  public Briefs getBriefs() {
    return briefs;
  }

  /**
   * Sets the value of the briefs property.
   *
   * @param value allowed object is
   *              {@link Briefs }
   */
  public void setBriefs(Briefs value) {
    this.briefs = value;
  }

  public UserContextsDto withBriefs(Briefs value) {
    setBriefs(value);
    return this;
  }

  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="brief" maxOccurs="unbounded" minOccurs="0"&gt;
   *           &lt;complexType&gt;
   *             &lt;complexContent&gt;
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                 &lt;sequence&gt;
   *                   &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                   &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                 &lt;/sequence&gt;
   *               &lt;/restriction&gt;
   *             &lt;/complexContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
          "brief"
  })
  public static class Briefs {

    protected List<Brief> brief;

    /**
     * Default no-arg constructor
     */
    public Briefs() {
      super();
    }

    /**
     * Fully-initialising value constructor
     */
    public Briefs(final List<Brief> brief) {
      this.brief = brief;
    }

    /**
     * Gets the value of the brief property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the brief property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBrief().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Brief }
     */
    public List<Brief> getBrief() {
      if (brief == null) {
        brief = new ArrayList<>();
      }
      return this.brief;
    }

    public Briefs withBrief(Brief... values) {
      if (values != null) {
        for (Brief value : values) {
          getBrief().add(value);
        }
      }
      return this;
    }

    public Briefs withBrief(Collection<Brief> values) {
      if (values != null) {
        getBrief().addAll(values);
      }
      return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "organization",
            "name",
            "state",
            "href",
            "grantedPermissions",
            "domainRestrictions",
            "domainsUsed"
    })
    public static class Brief {

      @XmlElement(required = true)
      protected String organization;
      @XmlElement(required = true)
      protected String name;
      @XmlElement(required = true)
      protected String state;
      @XmlElement(required = true)
      protected String href;
      @XmlElement(required = true)
      protected GrantedPermissions grantedPermissions;
      @XmlElement(required = true)
      protected DomainRestrictionsDto domainRestrictions;
      protected boolean domainsUsed;

      /**
       * Default no-arg constructor
       */
      public Brief() {
        super();
      }

      /**
       * Fully-initialising value constructor
       */
      public Brief(final String organization, final String name, final String state, final String href,
                   final GrantedPermissions grantedPermissions,
                   final DomainRestrictionsDto domainRestrictions, final boolean domainsUsed) {
        this.organization = organization;
        this.name = name;
        this.state = state;
        this.href = href;
        this.grantedPermissions = grantedPermissions;
        this.domainRestrictions = domainRestrictions;
        this.domainsUsed = domainsUsed;
      }

      /**
       * Gets the value of the organization property.
       *
       * @return possible object is
       * {@link String }
       */
      public String getOrganization() {
        return organization;
      }

      /**
       * Sets the value of the organization property.
       *
       * @param value allowed object is
       *              {@link String }
       */
      public void setOrganization(String value) {
        this.organization = value;
      }

      /**
       * Gets the value of the name property.
       *
       * @return possible object is
       * {@link String }
       */
      public String getName() {
        return name;
      }

      /**
       * Sets the value of the name property.
       *
       * @param value allowed object is
       *              {@link String }
       */
      public void setName(String value) {
        this.name = value;
      }

      /**
       * Gets the value of the state property.
       *
       * @return possible object is
       * {@link String }
       */
      public String getState() {
        return state;
      }

      /**
       * Sets the value of the state property.
       *
       * @param value allowed object is
       *              {@link String }
       */
      public void setState(String value) {
        this.state = value;
      }

      /**
       * Gets the value of the href property.
       *
       * @return possible object is
       * {@link String }
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       *
       * @param value allowed object is
       *              {@link String }
       */
      public void setHref(String value) {
        this.href = value;
      }

      /**
       * Obtient la valeur de la propriété grantedPermissions.
       *
       * @return
       *     possible object is
       *     {@link GrantedPermissions }
       *
       */
      public GrantedPermissions getGrantedPermissions() {
        return grantedPermissions;
      }

      /**
       * Définit la valeur de la propriété grantedPermissions.
       *
       * @param value
       *     allowed object is
       *     {@link GrantedPermissions }
       *
       */
      public void setGrantedPermissions(GrantedPermissions value) {
        this.grantedPermissions = value;
      }

      /**
       * Obtient la valeur de la propriété domainRestrictions.
       *
       * @return
       *     possible object is
       *     {@link DomainRestrictionsDto }
       *
       */
      public DomainRestrictionsDto getDomainRestrictions() {
        return domainRestrictions;
      }

      /**
       * Définit la valeur de la propriété domainRestrictions.
       *
       * @param value
       *     allowed object is
       *     {@link DomainRestrictionsDto }
       *
       */
      public void setDomainRestrictions(DomainRestrictionsDto value) {
        this.domainRestrictions = value;
      }

      /**
       * Obtient la valeur de la propriété domainsUsed.
       *
       */
      public boolean isDomainsUsed() {
        return domainsUsed;
      }

      /**
       * Définit la valeur de la propriété domainsUsed.
       *
       */
      public void setDomainsUsed(boolean value) {
        this.domainsUsed = value;
      }

      public Brief withOrganization(String value) {
        setOrganization(value);
        return this;
      }

      public Brief withName(String value) {
        setName(value);
        return this;
      }

      public Brief withState(String value) {
        setState(value);
        return this;
      }

      public Brief withHref(String value) {
        setHref(value);
        return this;
      }

      public Brief withGrantedPermissions(GrantedPermissions value) {
        setGrantedPermissions(value);
        return this;
      }

      public Brief withDomainRestrictions(DomainRestrictionsDto value) {
        setDomainRestrictions(value);
        return this;
      }

      public Brief withDomainsUsed(boolean value) {
        setDomainsUsed(value);
        return this;
      }

      /**
       * <p>Classe Java pour anonymous complex type.
       *
       * <p>Le fragment de schéma suivant indique le contenu attendu figurant dans cette classe.
       *
       * <pre>
       * &lt;complexType&gt;
       *   &lt;complexContent&gt;
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
       *       &lt;sequence&gt;
       *         &lt;element name="permission" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
       *       &lt;/sequence&gt;
       *     &lt;/restriction&gt;
       *   &lt;/complexContent&gt;
       * &lt;/complexType&gt;
       * </pre>
       *
       *
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = {
              "permission"
      })
      public static class GrantedPermissions {

        protected List<String> permission;

        /**
         * Default no-arg constructor
         *
         */
        public GrantedPermissions() {
          super();
        }

        /**
         * Fully-initialising value constructor
         *
         */
        public GrantedPermissions(final List<String> permission) {
          this.permission = permission;
        }

        /**
         * Gets the value of the permission property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the permission property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPermission().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         *
         *
         */
        public List<String> getPermission() {
          if (permission == null) {
            permission = new ArrayList<String>();
          }
          return this.permission;
        }

        public GrantedPermissions withPermission(String... values) {
          if (values!= null) {
            for (String value: values) {
              getPermission().add(value);
            }
          }
          return this;
        }

        public GrantedPermissions withPermission(Collection<String> values) {
          if (values!= null) {
            getPermission().addAll(values);
          }
          return this;
        }

      }

    }

  }

}
