//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 03:08:24 PM CET 
//


package com.actility.thingpark.smp.rest.dto.application;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for UserDto complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UserDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="lastConnection" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="thingparkID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="facebookID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="googleID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mobilePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="officePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="homePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="previousConnection" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="thingparkLastUnsuccessfulLogin" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="thingparkPreviousBadConsecutivePwd" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="disclaimerMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="disclaimerRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserDto", propOrder = {
        "state",
        "lastConnection",
        "gender",
        "firstName",
        "lastName",
        "language",
        "thingparkID",
        "facebookID",
        "googleID",
        "email",
        "mobilePhone",
        "officePhone",
        "homePhone",
        "organization",
        "previousConnection",
        "thingparkLastUnsuccessfulLogin",
        "thingparkPreviousBadConsecutivePwd",
        "disclaimerMessage",
        "disclaimerRequired"
})
@XmlRootElement(namespace = "http://www.actility.com/smp/ws/application", name = "user")
public class UserDto {

  @XmlElement(required = true)
  protected String state;
  @XmlElement(required = true)
  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar lastConnection;
  @XmlElement(required = true)
  protected String gender;
  @XmlElement(required = true)
  protected String firstName;
  @XmlElement(required = true)
  protected String lastName;
  @XmlElement(required = true)
  protected String language;
  @XmlElement(required = true)
  protected String thingparkID;
  @XmlElement(required = true)
  protected String facebookID;
  @XmlElement(required = true)
  protected String googleID;
  @XmlElement(required = true)
  protected String email;
  @XmlElement(required = true)
  protected String mobilePhone;
  @XmlElement(required = true)
  protected String officePhone;
  @XmlElement(required = true)
  protected String homePhone;
  @XmlElement(required = true)
  protected String organization;
  @XmlElement(required = true)
  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar previousConnection;
  @XmlElement(required = true)
  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar thingparkLastUnsuccessfulLogin;
  protected int thingparkPreviousBadConsecutivePwd;
  @XmlElement(required = true)
  protected String disclaimerMessage;
  protected boolean disclaimerRequired;

  /**
   * Default no-arg constructor
   */
  public UserDto() {
    super();
  }

  /**
   * Fully-initialising value constructor
   */
  public UserDto(final String state, final XMLGregorianCalendar lastConnection, final String gender, final String firstName, final String lastName, final String language, final String thingparkID, final String facebookID, final String googleID, final String email, final String mobilePhone, final String officePhone, final String homePhone, final String organization, final XMLGregorianCalendar previousConnection, final XMLGregorianCalendar thingparkLastUnsuccessfulLogin, final int thingparkPreviousBadConsecutivePwd, final String disclaimerMessage, final boolean disclaimerRequired) {
    this.state = state;
    this.lastConnection = lastConnection;
    this.gender = gender;
    this.firstName = firstName;
    this.lastName = lastName;
    this.language = language;
    this.thingparkID = thingparkID;
    this.facebookID = facebookID;
    this.googleID = googleID;
    this.email = email;
    this.mobilePhone = mobilePhone;
    this.officePhone = officePhone;
    this.homePhone = homePhone;
    this.organization = organization;
    this.previousConnection = previousConnection;
    this.thingparkLastUnsuccessfulLogin = thingparkLastUnsuccessfulLogin;
    this.thingparkPreviousBadConsecutivePwd = thingparkPreviousBadConsecutivePwd;
    this.disclaimerMessage = disclaimerMessage;
    this.disclaimerRequired = disclaimerRequired;
  }

  /**
   * Gets the value of the state property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getState() {
    return state;
  }

  /**
   * Sets the value of the state property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setState(String value) {
    this.state = value;
  }

  /**
   * Gets the value of the lastConnection property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getLastConnection() {
    return lastConnection;
  }

  /**
   * Sets the value of the lastConnection property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setLastConnection(XMLGregorianCalendar value) {
    this.lastConnection = value;
  }

  /**
   * Gets the value of the gender property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getGender() {
    return gender;
  }

  /**
   * Sets the value of the gender property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setGender(String value) {
    this.gender = value;
  }

  /**
   * Gets the value of the firstName property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the firstName property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setFirstName(String value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the lastName property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the lastName property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setLastName(String value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the language property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getLanguage() {
    return language;
  }

  /**
   * Sets the value of the language property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setLanguage(String value) {
    this.language = value;
  }

  /**
   * Gets the value of the thingparkID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getThingparkID() {
    return thingparkID;
  }

  /**
   * Sets the value of the thingparkID property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setThingparkID(String value) {
    this.thingparkID = value;
  }

  /**
   * Gets the value of the facebookID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getFacebookID() {
    return facebookID;
  }

  /**
   * Sets the value of the facebookID property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setFacebookID(String value) {
    this.facebookID = value;
  }

  /**
   * Gets the value of the googleID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getGoogleID() {
    return googleID;
  }

  /**
   * Sets the value of the googleID property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setGoogleID(String value) {
    this.googleID = value;
  }

  /**
   * Gets the value of the email property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getEmail() {
    return email;
  }

  /**
   * Sets the value of the email property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setEmail(String value) {
    this.email = value;
  }

  /**
   * Gets the value of the mobilePhone property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getMobilePhone() {
    return mobilePhone;
  }

  /**
   * Sets the value of the mobilePhone property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setMobilePhone(String value) {
    this.mobilePhone = value;
  }

  /**
   * Gets the value of the officePhone property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getOfficePhone() {
    return officePhone;
  }

  /**
   * Sets the value of the officePhone property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setOfficePhone(String value) {
    this.officePhone = value;
  }

  /**
   * Gets the value of the homePhone property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getHomePhone() {
    return homePhone;
  }

  /**
   * Sets the value of the homePhone property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setHomePhone(String value) {
    this.homePhone = value;
  }

  /**
   * Gets the value of the organization property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getOrganization() {
    return organization;
  }

  /**
   * Sets the value of the organization property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setOrganization(String value) {
    this.organization = value;
  }

  /**
   * Gets the value of the previousConnection property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getPreviousConnection() {
    return previousConnection;
  }

  /**
   * Sets the value of the previousConnection property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setPreviousConnection(XMLGregorianCalendar value) {
    this.previousConnection = value;
  }

  /**
   * Gets the value of the thingparkLastUnsuccessfulLogin property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getThingparkLastUnsuccessfulLogin() {
    return thingparkLastUnsuccessfulLogin;
  }

  /**
   * Sets the value of the thingparkLastUnsuccessfulLogin property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setThingparkLastUnsuccessfulLogin(XMLGregorianCalendar value) {
    this.thingparkLastUnsuccessfulLogin = value;
  }

  /**
   * Gets the value of the thingparkPreviousBadConsecutivePwd property.
   */
  public int getThingparkPreviousBadConsecutivePwd() {
    return thingparkPreviousBadConsecutivePwd;
  }

  /**
   * Sets the value of the thingparkPreviousBadConsecutivePwd property.
   */
  public void setThingparkPreviousBadConsecutivePwd(int value) {
    this.thingparkPreviousBadConsecutivePwd = value;
  }

  /**
   * Gets the value of the disclaimerMessage property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getDisclaimerMessage() {
    return disclaimerMessage;
  }

  /**
   * Sets the value of the disclaimerMessage property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setDisclaimerMessage(String value) {
    this.disclaimerMessage = value;
  }

  /**
   * Gets the value of the disclaimerRequired property.
   */
  public boolean isDisclaimerRequired() {
    return disclaimerRequired;
  }

  /**
   * Sets the value of the disclaimerRequired property.
   */
  public void setDisclaimerRequired(boolean value) {
    this.disclaimerRequired = value;
  }

  public UserDto withState(String value) {
    setState(value);
    return this;
  }

  public UserDto withLastConnection(XMLGregorianCalendar value) {
    setLastConnection(value);
    return this;
  }

  public UserDto withGender(String value) {
    setGender(value);
    return this;
  }

  public UserDto withFirstName(String value) {
    setFirstName(value);
    return this;
  }

  public UserDto withLastName(String value) {
    setLastName(value);
    return this;
  }

  public UserDto withLanguage(String value) {
    setLanguage(value);
    return this;
  }

  public UserDto withThingparkID(String value) {
    setThingparkID(value);
    return this;
  }

  public UserDto withFacebookID(String value) {
    setFacebookID(value);
    return this;
  }

  public UserDto withGoogleID(String value) {
    setGoogleID(value);
    return this;
  }

  public UserDto withEmail(String value) {
    setEmail(value);
    return this;
  }

  public UserDto withMobilePhone(String value) {
    setMobilePhone(value);
    return this;
  }

  public UserDto withOfficePhone(String value) {
    setOfficePhone(value);
    return this;
  }

  public UserDto withHomePhone(String value) {
    setHomePhone(value);
    return this;
  }

  public UserDto withOrganization(String value) {
    setOrganization(value);
    return this;
  }

  public UserDto withPreviousConnection(XMLGregorianCalendar value) {
    setPreviousConnection(value);
    return this;
  }

  public UserDto withThingparkLastUnsuccessfulLogin(XMLGregorianCalendar value) {
    setThingparkLastUnsuccessfulLogin(value);
    return this;
  }

  public UserDto withThingparkPreviousBadConsecutivePwd(int value) {
    setThingparkPreviousBadConsecutivePwd(value);
    return this;
  }

  public UserDto withDisclaimerMessage(String value) {
    setDisclaimerMessage(value);
    return this;
  }

  public UserDto withDisclaimerRequired(boolean value) {
    setDisclaimerRequired(value);
    return this;
  }

}
